[[redirects]]
  from = "https://basketballstarsunblocked.netlify.app/*"
  to = "https://basketballstarsunblocked.org/:splat"
  status = 301
  force = true

[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 